version: '3'

services:
  mongodb:
    image: mongo:4.1.1-xenial
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE="emial_sender"
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="password!"
    volumes:
      - ./data/db:/data/db
      - ./docker/mongo/init:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017